Switch to IP-based etcd TLS testing
- Commented out the use of `$TARGET` for generating SANs in the
pre-start script to prevent bosh link issues.
- Modified the etcd TLS test script to resolve and use the IP address
of `$TARGET`.
- Added error handling to ensure the script exits if the IP address
resolution fails.
- This change addresses situations where the TLS certificate includes
the IP in the SAN but not the hostname, avoiding TLS verification errors

diff --git a/jobs/tests/templates/tests/etcd b/jobs/tests/templates/tests/etcd
--- a/jobs/tests/templates/tests/etcd
+++ b/jobs/tests/templates/tests/etcd
@@ -230,8 +230,17 @@ runTests etcd-notls http://$TARGET:2379
 rc=$?
 echo
 
-echo "Testing etcd with tls..."
-runTests etcd-tls https://$TARGET:2479
+echo "Testing etcd with TLS..."
+echo "Using IP address of $TARGET"
+shield_ip=$(getent hosts "$TARGET" | awk '{ print $1 }')
+
+if [ -z "$shield_ip" ]; then
+    echo "Error: Could not resolve IP address for $TARGET."
+    exit 1
+fi
+
+echo "Running tests with IP $shield_ip"
+runTests etcd-tls https://$shield_ip:2479
 rc=$(($rc + $?))
 
 exit $rc
